obj-m += mmr_memtap_loopback.o

# Usage (on MiSTer/Linux kernel source tree):
#   make -C /lib/modules/$(uname -r)/build M=$(PWD) modules
#   sudo insmod mmr_memtap_loopback.ko nes_path=/tmp/nes_cpu_ram.bin
#   ls -l /dev/mmr_memtap

